=== rtbn12/LABI/Lab_4/timetable.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="timetable">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="day" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="day">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="lesson" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="dayOfWeek" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="lesson">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="timeFrom"/>
                <xs:element ref="timeTo"/>
                <xs:element ref="subject"/>
                <xs:element ref="teacher"/>
                <xs:element ref="room" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="type" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="timeFrom" type="xs:string"/>
    <xs:element name="timeTo"   type="xs:string"/>
    <xs:element name="subject"  type="xs:string"/>
    <xs:element name="teacher"  type="xs:string"/>
    <xs:element name="room"     type="xs:string"/>

</xs:schema>

=== rtbn12/LABI/Lab_4/timetable2.xml
<?xml version="1.0" encoding="UTF-8"?>
<timetable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="timetable.xsd">

    <day dayOfWeek="Monday">
        <lesson type="practical">
            <timeFrom>08.00</timeFrom>
            <timeTo>09.30</timeTo>
            <subject>Deutsch</subject>
            <teacher>Borisova</teacher>
            <room>216</room>
        </lesson>
        <lesson type="lecture">
            <timeFrom>09.40</timeFrom>
            <timeTo>11.10</timeTo>
            <subject>SAP Administration</subject>
            <teacher>Egorov</teacher>
            <room>384</room>
        </lesson>
        <lesson type="practical">
            <timeFrom>11.20</timeFrom>
            <timeTo>12.50</timeTo>
            <subject>SAP Administration</subject>
            <teacher>Petrov</teacher>
            <room>384</room>
        </lesson>
    </day>

</timetable>
